DELETE FROM store_returns where SR_TICKET_NUMBER IN (SELECT SS_TICKET_NUMBER FROM store_sales, date_dim WHERE SS_SOLD_DATE_SK=D_DATE_SK AND D_DATE BETWEEN CAST('${param1}' AS DATE) AND CAST('${param2}' AS DATE));
DELETE FROM store_sales where SS_SOLD_DATE_SK >= (SELECT mIN(D_DATE_SK) FROM date_dim WHERE D_DATE BETWEEN CAST('${param1}' AS DATE) AND CAST('${param2}' AS DATE)) AND
                SS_SOLD_DATE_SK <= (SELECT MAX(D_DATE_SK) FROM date_dim WHERE D_DATE BETWEEN CAST('${param1}' AS DATE) AND CAST('${param2}' AS DATE));

DELETE FROM store_returns where SR_TICKET_NUMBER IN (SELECT SS_TICKET_NUMBER FROM store_sales, date_dim WHERE SS_SOLD_DATE_SK=D_DATE_SK AND D_DATE BETWEEN CAST('${param3}' AS DATE) AND CAST('${param4}' AS DATE));
DELETE FROM store_sales where SS_SOLD_DATE_SK >= (SELECT mIN(D_DATE_SK) FROM date_dim WHERE D_DATE BETWEEN CAST('${param3}' AS DATE) AND CAST('${param4}' AS DATE)) AND
                SS_SOLD_DATE_SK<= (SELECT MAX(D_DATE_SK) FROM date_dim WHERE D_DATE BETWEEN CAST('${param3}' AS DATE) AND CAST('${param4}' AS DATE));

DELETE FROM store_returns where SR_TICKET_NUMBER IN (SELECT SS_TICKET_NUMBER FROM store_sales, date_dim WHERE SS_SOLD_DATE_SK=D_DATE_SK AND D_DATE BETWEEN CAST('${param5}' AS DATE) AND CAST('${param6}' AS DATE));
DELETE FROM store_sales where SS_SOLD_DATE_SK >= (SELECT mIN(D_DATE_SK) FROM date_dim WHERE D_DATE BETWEEN CAST('${param5}' AS DATE) AND CAST('${param6}' AS DATE)) AND
                SS_SOLD_DATE_SK <= (SELECT MAX(D_DATE_SK) FROM date_dim WHERE D_DATE BETWEEN CAST('${param5}' AS DATE) AND CAST('${param6}' AS DATE));