DELETE FROM web_returns WHERE WR_ORDER_NUMBER IN (SELECT WS_ORDER_NUMBER FROM web_sales, date_dim WHERE WS_SOLD_DATE_SK=D_DATE_SK AND D_DATE BETWEEN CAST('${param1}' AS DATE) AND CAST('${param2}' AS DATE));
DELETE FROM web_sales WHERE WS_SOLD_DATE_SK >= (SELECT MIN(D_DATE_SK) FROM date_dim WHERE D_DATE BETWEEN CAST('${param1}' AS DATE) AND CAST('${param2}' AS DATE)) AND
                 WS_SOLD_DATE_SK <= (SELECT max(D_DATE_SK) FROM date_dim WHERE D_DATE BETWEEN CAST('${param1}' AS DATE) AND CAST('${param2}' AS DATE));

DELETE FROM web_returns WHERE WR_ORDER_NUMBER IN (SELECT WS_ORDER_NUMBER FROM web_sales, date_dim WHERE WS_SOLD_DATE_SK=D_DATE_SK AND D_DATE BETWEEN CAST('${param3}' AS DATE) AND CAST('${param4}' AS DATE));
DELETE FROM web_sales WHERE WS_SOLD_DATE_SK >= (SELECT MIN(D_DATE_SK) FROM date_dim WHERE D_DATE BETWEEN CAST('${param3}' AS DATE) AND CAST('${param4}' AS DATE)) AND
                WS_SOLD_DATE_SK <= (SELECT max(D_DATE_SK) FROM date_dim WHERE D_DATE BETWEEN CAST('${param3}' AS DATE) AND CAST('${param4}' AS DATE));

DELETE FROM web_returns WHERE WR_ORDER_NUMBER IN (SELECT WS_ORDER_NUMBER FROM web_sales, date_dim WHERE WS_SOLD_DATE_SK=D_DATE_SK AND D_DATE BETWEEN CAST('${param5}' AS DATE) AND CAST('${param6}' AS DATE));
DELETE FROM web_sales WHERE WS_SOLD_DATE_SK >= (SELECT MIN(D_DATE_SK) FROM date_dim WHERE D_DATE BETWEEN CAST('${param5}' AS DATE) AND CAST('${param6}' AS DATE)) AND
                WS_SOLD_DATE_SK <= (SELECT max(D_DATE_SK) FROM date_dim WHERE D_DATE BETWEEN CAST('${param5}' AS DATE) AND CAST('${param6}' AS DATE));