DROP VIEW IF EXISTS crv_${stream_num};

CREATE VIEW crv_${stream_num}
AS SELECT D_DATE_SK CR_RETURN_DATE_SK
,T_TIME_SK CR_RETURN_TIME_SK
,I_ITEM_SK CR_ITEM_SK
,c1.C_CUSTOMER_SK CR_REFUNDED_CUSTOMER_SK
,c1.C_CURRENT_CDEMO_SK CR_REFUNDED_CDEMO_SK
,c1.C_CURRENT_HDEMO_SK CR_REFUNDED_HDEMO_SK
,c1.C_CURRENT_ADDR_SK CR_REFUNDED_ADDR_SK
,c2.C_CUSTOMER_SK CR_RETURNING_CUSTOMER_SK
,c2.C_CURRENT_CDEMO_SK CR_RETURNING_CDEMO_SK
,c2.C_CURRENT_HDEMO_SK CR_RETURNING_HDEMO_SK
,c2.C_CURRENT_ADDR_SK CR_RETURNING_ADDR_SK
,CC_CALL_CENTER_SK CR_CALL_CENTER_SK
,CP_CATALOG_PAGE_SK CR_CATALOG_PAGE_SK
,SM_SHIP_MODE_SK CR_SHIP_MODE_SK
,W_WAREHOUSE_SK CR_WAREHOUSE_SK
,R_REASON_SK CR_REASON_SK
,CRET_ORDER_ID CR_ORDER_NUMBER
,CRET_RETURN_QTY CR_RETURN_QUANTITY
,CRET_RETURN_AMT CR_RETURN_AMOUNT
,CRET_RETURN_TAX CR_RETURN_TAX
,(CRET_RETURN_AMT + CRET_RETURN_TAX) AS CR_RETURN_AMT_INC_TAX
,CRET_RETURN_FEE CR_FEE
,CRET_RETURN_SHIP_COST CR_RETURN_SHIP_COST
,CRET_REFUNDED_CASH CR_REFUNDED_CASH
,CRET_REVERSED_CHARGE CR_REVERSED_CHARGE
,CRET_MERCHANT_CREDIT CR_MERCHANT_CREDIT
,(CRET_RETURN_AMT+CRET_RETURN_TAX+CRET_RETURN_FEE-CRET_REFUNDED_CASH-CRET_REVERSED_CHARGE-CRET_MERCHANT_CREDIT) CR_NET_LOSS
FROM s_catalog_returns_${stream_num}
LEFT OUTER JOIN date_dim
ON (CAST(CRET_RETURN_DATE AS DATE) = D_DATE)
LEFT OUTER JOIN time_dim ON
((CAST(SUBSTRING(CRET_RETURN_TIME,1,2) AS INTEGER)*3600
+CAST(SUBSTRING(CRET_RETURN_TIME,4,2) AS INTEGER)*60
+CAST(SUBSTRING(CRET_RETURN_TIME,7,2) AS INTEGER)) = T_TIME)
LEFT OUTER JOIN item ON (CRET_ITEM_ID = I_ITEM_ID)
LEFT OUTER JOIN customer c1 ON (CRET_RETURN_CUSTOMER_ID = c1.C_CUSTOMER_ID)
LEFT OUTER JOIN customer c2 ON (CRET_REFUND_CUSTOMER_ID = c2.C_CUSTOMER_ID)
LEFT OUTER JOIN reason ON (CRET_REASON_ID = R_REASON_ID)
LEFT OUTER JOIN call_center ON (CRET_CALL_CENTER_ID = CC_CALL_CENTER_ID)
LEFT OUTER JOIN catalog_page ON (CRET_CATALOG_PAGE_ID = CP_CATALOG_PAGE_ID)
LEFT OUTER JOIN ship_mode ON (CRET_SHIPMODE_ID = SM_SHIP_MODE_ID)
LEFT OUTER JOIN warehouse ON (CRET_WAREHOUSE_ID = W_WAREHOUSE_ID)
WHERE I_REC_END_DATE IS NULL AND CC_REC_END_DATE IS NULL;

INSERT INTO catalog_returns SELECT
CR_RETURN_DATE_SK,CR_RETURN_TIME_SK,CR_ITEM_SK,CR_REFUNDED_CUSTOMER_SK,CR_REFUNDED_CDEMO_SK,CR_REFUNDED_HDEMO_SK,CR_REFUNDED_ADDR_SK,CR_RETURNING_CUSTOMER_SK,CR_RETURNING_CDEMO_SK,CR_RETURNING_HDEMO_SK,CR_RETURNING_ADDR_SK,CR_CALL_CENTER_SK,CR_CATALOG_PAGE_SK,CR_SHIP_MODE_SK,CR_WAREHOUSE_SK,CR_REASON_SK,CR_ORDER_NUMBER,CR_RETURN_QUANTITY,CR_RETURN_AMOUNT,CR_RETURN_TAX,CR_RETURN_AMT_INC_TAX,CR_FEE,CR_RETURN_SHIP_COST,CR_REFUNDED_CASH,CR_REVERSED_CHARGE,CR_MERCHANT_CREDIT,CR_NET_LOSS
FROM crv_${stream_num};