DROP VIEW IF EXISTS srv_${stream_num};

CREATE VIEW srv_${stream_num}
AS SELECT D_DATE_SK SR_RETURNED_DATE_SK
,T_TIME_SK SR_RETURN_TIME_SK
,I_ITEM_SK SR_ITEM_SK
,C_CUSTOMER_SK SR_CUSTOMER_SK
,C_CURRENT_CDEMO_SK SR_CDEMO_SK
,C_CURRENT_HDEMO_SK SR_HDEMO_SK
,C_CURRENT_ADDR_SK SR_ADDR_SK
,S_STORE_SK SR_STORE_SK
,R_REASON_SK SR_REASON_SK
,CAST(SRET_TICKET_NUMBER AS BIGINT) SR_TICKET_NUMBER
,SRET_RETURN_QTY SR_RETURN_QUANTITY
,(SRET_RETURN_AMT) SR_RETURN_AMT
,(SRET_RETURN_TAX) SR_RETURN_TAX
,(SRET_RETURN_AMT + SRET_RETURN_TAX) SR_RETURN_AMT_INC_TAX
,(SRET_RETURN_FEE) SR_FEE
,(SRET_RETURN_SHIP_COST) SR_RETURN_SHIP_COST
,(SRET_REFUNDED_CASH) SR_REFUNDED_CASH
,(SRET_REVERSED_CHARGE) SR_REVERSED_CHARGE
,(SRET_STORE_CREDIT) SR_STORE_CREDIT
,(SRET_RETURN_AMT+SRET_RETURN_TAX+SRET_RETURN_FEE-SRET_REFUNDED_CASH-SRET_REVERSED_CHARGE-SRET_STORE_CREDIT) SR_NET_LOSS
FROM s_store_returns_${stream_num}
LEFT OUTER JOIN date_dim
ON (CAST(SRET_RETURN_DATE AS DATE) = D_DATE)
LEFT OUTER JOIN time_dim
ON (( CAST(SUBSTRING(SRET_RETURN_TIME,1,2) AS INTEGER)*3600
+CAST(SUBSTRING(SRET_RETURN_TIME,4,2) AS INTEGER)*60
+CAST(SUBSTRING(SRET_RETURN_TIME,7,2) AS INTEGER)) = T_TIME)
LEFT OUTER JOIN item ON (SRET_ITEM_ID = I_ITEM_ID)
LEFT OUTER JOIN customer ON (SRET_CUSTOMER_ID = C_CUSTOMER_ID)
LEFT OUTER JOIN store ON (SRET_STORE_ID = S_STORE_ID)
LEFT OUTER JOIN reason ON (SRET_REASON_ID = R_REASON_ID)
WHERE I_REC_END_DATE IS NULL
AND S_REC_END_DATE IS NULL;

INSERT INTO store_returns SELECT
SR_RETURNED_DATE_SK, SR_RETURN_TIME_SK,SR_ITEM_SK,SR_CUSTOMER_SK,SR_CDEMO_SK,SR_HDEMO_SK,SR_ADDR_SK,SR_STORE_SK,SR_REASON_SK,SR_TICKET_NUMBER,SR_RETURN_QUANTITY,SR_RETURN_AMT,SR_RETURN_TAX,SR_RETURN_AMT_INC_TAX,SR_FEE,SR_RETURN_SHIP_COST,SR_REFUNDED_CASH,SR_REVERSED_CHARGE,SR_STORE_CREDIT,SR_NET_LOSS
FROM srv_${stream_num};