DROP VIEW IF EXISTS wrv_${stream_num};

CREATE VIEW wrv_${stream_num}
AS SELECT D_DATE_SK WR_RETURN_DATE_SK
,T_TIME_SK WR_RETURN_TIME_SK
,I_ITEM_SK WR_ITEM_SK
,c1.C_CUSTOMER_SK WR_REFUNDED_CUSTOMER_SK
,c1.C_CURRENT_CDEMO_SK WR_REFUNDED_CDEMO_SK
,c1.C_CURRENT_HDEMO_SK WR_REFUNDED_HDEMO_SK
,c1.C_CURRENT_ADDR_SK WR_REFUNDED_ADDR_SK
,c2.C_CUSTOMER_SK WR_RETURNING_CUSTOMER_SK
,c2.C_CURRENT_CDEMO_SK WR_RETURNING_CDEMO_SK
,c2.C_CURRENT_HDEMO_SK WR_RETURNING_HDEMO_SK
,c2.C_CURRENT_ADDR_SK WR_RETURNING_ADDR_SK
,WP_WEB_PAGE_SK WR_WEB_PAGE_SK
,R_REASON_SK WR_REASON_SK
,WRET_ORDER_ID WR_ORDER_NUMBER
,WRET_RETURN_QTY WR_RETURN_QUANTITY
,(WRET_RETURN_AMT) WR_RETURN_AMT
,(WRET_RETURN_TAX) WR_RETURN_TAX
,(WRET_RETURN_AMT + WRET_RETURN_TAX) AS WR_RETURN_AMT_INC_TAX
,(WRET_RETURN_FEE) WR_FEE
,(WRET_RETURN_SHIP_COST) WR_RETURN_SHIP_COST
,(WRET_REFUNDED_CASH) WR_REFUNDED_CASH
,(WRET_REVERSED_CHARGE) WR_REVERSED_CHARGE
,(WRET_ACCOUNT_CREDIT) WR_ACCOUNT_CREDIT
,(WRET_RETURN_AMT+WRET_RETURN_TAX+WRET_RETURN_FEE-WRET_REFUNDED_CASH-WRET_REVERSED_CHARGE-WRET_ACCOUNT_CREDIT) WR_NET_LOSS
FROM s_web_returns_${stream_num}
LEFT OUTER JOIN date_dim ON (CAST(WRET_RETURN_DATE AS DATE) = D_DATE)
LEFT OUTER JOIN time_dim ON ((CAST(SUBSTRING(WRET_RETURN_TIME,1,2) AS INTEGER)*3600
+CAST(SUBSTRING(WRET_RETURN_TIME,4,2) AS INTEGER)*60+CAST(SUBSTRING(WRET_RETURN_TIME,7,2) AS INTEGER))=T_TIME)
LEFT OUTER JOIN item ON (WRET_ITEM_ID = I_ITEM_ID)
LEFT OUTER JOIN customer c1 ON (WRET_RETURN_CUSTOMER_ID = c1.C_CUSTOMER_ID)
LEFT OUTER JOIN customer c2 ON (WRET_REFUND_CUSTOMER_ID = c2.C_CUSTOMER_ID)
LEFT OUTER JOIN reason ON (WRET_REASON_ID = R_REASON_ID)
LEFT OUTER JOIN web_page ON (WRET_WEB_SITE_ID = WP_WEB_PAGE_ID)
WHERE I_REC_END_DATE IS NULL AND WP_REC_END_DATE IS NULL;

INSERT INTO web_returns SELECT
WR_RETURN_DATE_SK,WR_RETURN_TIME_SK,WR_ITEM_SK,WR_REFUNDED_CUSTOMER_SK,WR_REFUNDED_CDEMO_SK,WR_REFUNDED_HDEMO_SK,WR_REFUNDED_ADDR_SK,WR_RETURNING_CUSTOMER_SK,WR_RETURNING_CDEMO_SK,WR_RETURNING_HDEMO_SK,WR_RETURNING_ADDR_SK,WR_WEB_PAGE_SK,WR_REASON_SK,WR_ORDER_NUMBER,WR_RETURN_QUANTITY,WR_RETURN_AMT,WR_RETURN_TAX,WR_RETURN_AMT_INC_TAX,WR_FEE,WR_RETURN_SHIP_COST,WR_REFUNDED_CASH,WR_REVERSED_CHARGE,WR_ACCOUNT_CREDIT,WR_NET_LOSS
FROM wrv_${stream_num};