CREATE
    VIEW ssv_${stream_num} AS SELECT
        D_DATE_SK SS_SOLD_DATE_SK,
        T_TIME_SK SS_SOLD_TIME_SK,
        I_ITEM_SK SS_ITEM_SK,
        C_CUSTOMER_SK SS_CUSTOMER_SK,
        C_CURRENT_CDEMO_SK SS_CDEMO_SK,
        C_CURRENT_HDEMO_SK SS_HDEMO_SK,
        C_CURRENT_ADDR_SK SS_ADDR_SK,
        S_STORE_SK SS_STORE_SK,
        P_PROMO_SK SS_PROMO_SK,
        PURC_PURCHASE_ID SS_TICKET_NUMBER,
        PLIN_QUANTITY SS_QUANTITY,
        (I_WHOLESALE_COST) SS_WHOLESALE_COST,
        (I_CURRENT_PRICE) SS_LIST_PRICE,
        (PLIN_SALE_PRICE) SS_SALES_PRICE,
        ((I_CURRENT_PRICE-PLIN_SALE_PRICE)*PLIN_QUANTITY) SS_EXT_DISCOUNT_AMT,
        (PLIN_SALE_PRICE * PLIN_QUANTITY) SS_EXT_SALES_PRICE,
        (I_WHOLESALE_COST * PLIN_QUANTITY) SS_EXT_WHOLESALE_COST,
        (I_CURRENT_PRICE * PLIN_QUANTITY) SS_EXT_LIST_PRICE,
        (I_CURRENT_PRICE * S_TAX_PRECENTAGE) SS_EXT_TAX,
        (PLIN_COUPON_AMT) SS_COUPON_AMT,
        ((PLIN_SALE_PRICE * PLIN_QUANTITY)-PLIN_COUPON_AMT) SS_NET_PAID,
        (((PLIN_SALE_PRICE * PLIN_QUANTITY)-PLIN_COUPON_AMT)*(1+S_TAX_PRECENTAGE)) SS_NET_PAID_INC_TAX,
        (((PLIN_SALE_PRICE * PLIN_QUANTITY)-PLIN_COUPON_AMT)-(PLIN_QUANTITY*I_WHOLESALE_COST)) SS_NET_PROFIT,
        row_number() over (order by D_DATE_SK, T_TIME_SK, I_ITEM_SK, C_CUSTOMER_SK) row_number
    FROM
        s_purchase_${stream_num}
    LEFT OUTER JOIN customer ON (PURC_CUSTOMER_ID = C_CUSTOMER_ID)
    LEFT OUTER JOIN store ON (PURC_STORE_ID = S_STORE_ID)
    LEFT OUTER JOIN date_dim ON (CAST(PURC_PURCHASE_DATE AS DATE) = D_DATE)
    LEFT OUTER JOIN time_dim ON (PURC_PURCHASE_TIME = T_TIME)
    JOIN s_purchase_lineitem_${stream_num} ON (PURC_PURCHASE_ID = PLIN_PURCHASE_ID)
    LEFT OUTER JOIN promotion ON PLIN_PROMOTION_ID = P_PROMO_ID
    LEFT OUTER JOIN item ON PLIN_ITEM_ID = I_ITEM_ID
    WHERE
        PURC_PURCHASE_ID = PLIN_PURCHASE_ID
        AND I_REC_END_DATE IS NULL
        AND S_REC_END_DATE IS NULL;
