CREATE
    VIEW wsv_${stream_num} AS SELECT
        d1.D_DATE_SK WS_SOLD_DATE_SK,
        T_TIME_SK WS_SOLD_TIME_SK,
        d2.D_DATE_SK WS_SHIP_DATE_SK,
        I_ITEM_SK WS_ITEM_SK,
        c1.C_CUSTOMER_SK WS_BILL_CUSTOMER_SK,
        c1.C_CURRENT_CDEMO_SK WS_BILL_CDEMO_SK,
        c1.C_CURRENT_HDEMO_SK WS_BILL_HDEMO_SK,
        c1.C_CURRENT_ADDR_SK WS_BILL_ADDR_SK,
        c2.C_CUSTOMER_SK WS_SHIP_CUSTOMER_SK,
        c2.C_CURRENT_CDEMO_SK WS_SHIP_CDEMO_SK,
        c2.C_CURRENT_HDEMO_SK WS_SHIP_HDEMO_SK,
        c2.C_CURRENT_ADDR_SK WS_SHIP_ADDR_SK,
        WP_WEB_PAGE_SK WS_WEB_PAGE_SK,
        WEB_SITE_SK WS_WEB_SITE_SK,
        SM_SHIP_MODE_SK WS_SHIP_MODE_SK,
        W_WAREHOUSE_SK WS_WAREHOUSE_SK,
        P_PROMO_SK WS_PROMO_SK,
        WORD_ORDER_ID WS_ORDER_NUMBER,
        WLIN_QUANTITY WS_QUANTITY,
        (I_WHOLESALE_COST) WS_WHOLESALE_COST,
        (I_CURRENT_PRICE) WS_LIST_PRICE,
        (WLIN_SALES_PRICE) WS_SALES_PRICE,
        ((I_CURRENT_PRICE-WLIN_SALES_PRICE)*WLIN_QUANTITY) WS_EXT_DISCOUNT_AMT,
        (WLIN_SALES_PRICE * WLIN_QUANTITY) WS_EXT_SALES_PRICE,
        (I_WHOLESALE_COST * WLIN_QUANTITY) WS_EXT_WHOLESALE_COST,
        (I_CURRENT_PRICE * WLIN_QUANTITY) WS_EXT_LIST_PRICE,
        (I_CURRENT_PRICE * WEB_TAX_PERCENTAGE) WS_EXT_TAX,
        (WLIN_COUPON_AMT) WS_COUPON_AMT,
        (WLIN_SHIP_COST * WLIN_QUANTITY) WS_EXT_SHIP_COST,
        ((WLIN_SALES_PRICE * WLIN_QUANTITY)-WLIN_COUPON_AMT) WS_NET_PAID,
        (((WLIN_SALES_PRICE * WLIN_QUANTITY)-WLIN_COUPON_AMT)*(1+WEB_TAX_PERCENTAGE)) WS_NET_PAID_INC_TAX,
        (((WLIN_SALES_PRICE * WLIN_QUANTITY)-WLIN_COUPON_AMT)-(WLIN_QUANTITY*I_WHOLESALE_COST)) WS_NET_PAID_INC_SHIP,
        ((WLIN_SALES_PRICE * WLIN_QUANTITY)-WLIN_COUPON_AMT + (WLIN_SHIP_COST * WLIN_QUANTITY) + I_CURRENT_PRICE * WEB_TAX_PERCENTAGE) WS_NET_PAID_INC_SHIP_TAX,
        (((WLIN_SALES_PRICE * WLIN_QUANTITY)-WLIN_COUPON_AMT)-(I_WHOLESALE_COST * WLIN_QUANTITY)) WS_NET_PROFIT,
        row_number() over (order by d1.D_DATE_SK, T_TIME_SK, d2.D_DATE_SK, I_ITEM_SK, c1.C_CUSTOMER_SK) row_number
    FROM
        s_web_order_${stream_num}
    LEFT OUTER JOIN date_dim d1 ON (CAST(WORD_ORDER_DATE AS DATE) = d1.D_DATE)
    LEFT OUTER JOIN time_dim ON (WORD_ORDER_TIME = T_TIME)
    LEFT OUTER JOIN customer c1 ON (WORD_BILL_CUSTOMER_ID = c1.C_CUSTOMER_ID)
    LEFT OUTER JOIN customer c2 ON (WORD_SHIP_CUSTOMER_ID = c2.C_CUSTOMER_ID)
    LEFT OUTER JOIN web_site ON (WORD_WEB_SITE_ID = WEB_SITE_ID AND WEB_REC_END_DATE IS NULL)
    LEFT OUTER JOIN ship_mode ON (WORD_SHIP_MODE_ID = SM_SHIP_MODE_ID)
    JOIN s_web_order_lineitem_${stream_num} ON (WORD_ORDER_ID = WLIN_ORDER_ID)
    LEFT OUTER JOIN date_dim d2 ON (CAST(WLIN_SHIP_DATE AS DATE) = d2.D_DATE)
    LEFT OUTER JOIN item ON (WLIN_ITEM_ID = I_ITEM_ID AND I_REC_END_DATE IS NULL)
    LEFT OUTER JOIN web_page ON (WLIN_WEB_PAGE_ID = WP_WEB_PAGE_ID AND WP_REC_END_DATE IS NULL)
    LEFT OUTER JOIN warehouse ON (WLIN_WAREHOUSE_ID = W_WAREHOUSE_ID)
    LEFT OUTER JOIN promotion ON (WLIN_PROMOTION_ID = P_PROMO_ID);
