# Description: Connections Configuration
---
version: 1
connections:
- id: spark_0
  driver: org.apache.hive.jdbc.HiveDriver
  url: jdbc:hive2://127.0.0.1:10000
  username: ${DATABASE_USER:-spark_admin}
  password: ${DATABASE_PASSWORD}
- id: spark_1
  type: jdbc
  driver: org.apache.hive.jdbc.HiveDriver
  url: jdbc:hive2://127.0.0.1:10001
  username: admin
  password: p@ssw0rd1
- id: spark_2
  type: spark
  url: spark://127.0.0.1:7077
  config:
    spark.worker.timeout: "60"
