# Description: WP2: Resilience
---
version: 1
id: wp2_resilience
phases:
- id: init
  sessions:
  - tasks:
    - template_id: init
- id: build
  sessions:
  - tasks:
    - template_id: build
- id: single_user_1
  sessions:
  - tasks:
    - template_id: single_user
- id: data_maintenance_1
  sessions:
  - tasks:
    - template_id: data_maintenance
    - template_id: data_maintenance
- id: single_user_2
  sessions:
  - tasks:
    - template_id: single_user
- id: data_maintenance_2
  sessions:
  - tasks:
    - template_id: data_maintenance
    - template_id: data_maintenance
    - template_id: data_maintenance
    - template_id: data_maintenance
- id: single_user_3
  sessions:
  - tasks:
    - template_id: single_user
- id: data_maintenance_3
  sessions:
  - tasks:
    - template_id: data_maintenance
    - template_id: data_maintenance
    - template_id: data_maintenance
    - template_id: data_maintenance
    - template_id: data_maintenance
    - template_id: data_maintenance
- id: single_user_4
  sessions:
  - tasks:
    - template_id: single_user
