# Description: WP3: R/W concurrency
---
version: 1
id: wp3_rw_concurrency
phases:
- id: init
  sessions:
  - tasks:
    - template_id: init
- id: build
  sessions:
  - tasks:
    - template_id: build_iceberg
- id: single_user_1_data_maintenance_1
  sessions:
  - tasks:
    - template_id: single_user
  - tasks:
    - template_id: data_maintenance
    - template_id: data_maintenance
    target_endpoint: 1
- id: single_user_2_data_maintenance_2
  sessions:
  - tasks:
    - template_id: single_user
  - tasks:
    - template_id: data_maintenance
    - template_id: data_maintenance
    - template_id: data_maintenance
    - template_id: data_maintenance
    target_endpoint: 1
- id: single_user_3_data_maintenance_3
  sessions:
  - tasks:
    - template_id: single_user
  - tasks:
    - template_id: data_maintenance
    - template_id: data_maintenance
    - template_id: data_maintenance
    - template_id: data_maintenance
    - template_id: data_maintenance
    - template_id: data_maintenance
    target_endpoint: 1
