# Description: W0: Original TPC-H sequence (SF1000, S=7)
---
version: 1
id: w0_tpch_delta
phases:
- id: setup
  sessions:
  - tasks:
    - template_id: setup
- id: setup_data_maintenance
  sessions:
  - tasks:
    - template_id: setup_data_maintenance
    - template_id: setup_data_maintenance
    - template_id: setup_data_maintenance
    - template_id: setup_data_maintenance
    - template_id: setup_data_maintenance
    - template_id: setup_data_maintenance
    - template_id: setup_data_maintenance
    - template_id: setup_data_maintenance  
- id: init
  sessions:
  - tasks:
    - template_id: init
- id: build
  sessions:
  - tasks:
    - template_id: build
- id: power
  sessions:
  - tasks:
    - template_id: data_maintenance_1
    - template_id: single_user
    - template_id: data_maintenance_2_merge
- id: throughput
  sessions:
  - tasks:
    - template_id: single_user
  - tasks:
    - template_id: single_user
  - tasks:
    - template_id: single_user
  - tasks:
    - template_id: single_user
  - tasks:
    - template_id: single_user
  - tasks:
    - template_id: single_user
  - tasks:
    - template_id: single_user
  - tasks:
    - template_id: data_maintenance_1
    - template_id: data_maintenance_2_merge
    - template_id: data_maintenance_1
    - template_id: data_maintenance_2_merge
    - template_id: data_maintenance_1
    - template_id: data_maintenance_2_merge
    - template_id: data_maintenance_1
    - template_id: data_maintenance_2_merge
    - template_id: data_maintenance_1
    - template_id: data_maintenance_2_merge
    - template_id: data_maintenance_1
    - template_id: data_maintenance_2_merge
    - template_id: data_maintenance_1
    - template_id: data_maintenance_2_merge
