# Description: W0: Original TPC-DS sequence
---
version: 1
id: w0_tpcds_delta
phases:
- id: setup
  sessions:
  - tasks:
    - template_id: setup
- id: setup_data_maintenance
  sessions:
  - tasks:
    - template_id: setup_data_maintenance
    - template_id: setup_data_maintenance
    - template_id: setup_data_maintenance
    - template_id: setup_data_maintenance
- id: init
  sessions:
  - tasks:
    - template_id: init
- id: build
  sessions:
  - tasks:
    - template_id: build
- id: single_user
  sessions:
  - tasks:
    - template_id: single_user
- id: throughput_1
  sessions:
  - tasks:
    - template_id: single_user
      permute_order: true
  - tasks:
    - template_id: single_user
      permute_order: true
  - tasks:
    - template_id: single_user
      permute_order: true
  - tasks:
    - template_id: single_user
      permute_order: true
- id: data_maintenance_1
  sessions:
  - tasks:
    - template_id: data_maintenance_delta
    - template_id: data_maintenance_delta
- id: throughput_2
  sessions:
  - tasks:
    - template_id: single_user
      permute_order: true
  - tasks:
    - template_id: single_user
      permute_order: true
  - tasks:
    - template_id: single_user
      permute_order: true
  - tasks:
    - template_id: single_user
      permute_order: true
- id: data_maintenance_2
  sessions:
  - tasks:
    - template_id: data_maintenance_delta
    - template_id: data_maintenance_delta
