# Description: Library.
---
version: 1
task_templates:
# Create external tables needed for benchmark
- id: setup
  files:
  - run/snowflake-8.13.1/scripts/tpcds/setup/ddl-external-tables.sql
  - run/snowflake-8.13.1/scripts/tpcds/setup/populate-external-tables.sql
# Create data maintenance external tables needed for benchmark
- id: setup_data_maintenance
  files:
  - run/snowflake-8.13.1/scripts/tpcds/setup_data_maintenance/ddl-external-tables-refresh.sql
  - run/snowflake-8.13.1/scripts/tpcds/setup_data_maintenance/populate-external-tables-refresh.sql
  parameter_values_file: run/auxiliary/tpcds/setup_data_maintenance/parameter_values.dat
# Create schema and drop existing tables
- id: init
  files:
  - run/snowflake-8.13.1/scripts/tpcds/init/init.sql
# Create benchmark tables and load data into them
- id: build
  files:
  - run/snowflake-8.13.1/scripts/tpcds/build/1_create_call_center.sql
  - run/snowflake-8.13.1/scripts/tpcds/build/1_create_catalog_page.sql
  - run/snowflake-8.13.1/scripts/tpcds/build/1_create_catalog_returns.sql
  - run/snowflake-8.13.1/scripts/tpcds/build/1_create_catalog_sales.sql
  - run/snowflake-8.13.1/scripts/tpcds/build/1_create_customer.sql
  - run/snowflake-8.13.1/scripts/tpcds/build/1_create_customer_address.sql
  - run/snowflake-8.13.1/scripts/tpcds/build/1_create_customer_demographics.sql
  - run/snowflake-8.13.1/scripts/tpcds/build/1_create_date_dim.sql
  - run/snowflake-8.13.1/scripts/tpcds/build/1_create_household_demographics.sql
  - run/snowflake-8.13.1/scripts/tpcds/build/1_create_income_band.sql
  - run/snowflake-8.13.1/scripts/tpcds/build/1_create_inventory.sql
  - run/snowflake-8.13.1/scripts/tpcds/build/1_create_item.sql
  - run/snowflake-8.13.1/scripts/tpcds/build/1_create_promotion.sql
  - run/snowflake-8.13.1/scripts/tpcds/build/1_create_reason.sql
  - run/snowflake-8.13.1/scripts/tpcds/build/1_create_ship_mode.sql
  - run/snowflake-8.13.1/scripts/tpcds/build/1_create_store.sql
  - run/snowflake-8.13.1/scripts/tpcds/build/1_create_store_returns.sql
  - run/snowflake-8.13.1/scripts/tpcds/build/1_create_store_sales.sql
  - run/snowflake-8.13.1/scripts/tpcds/build/1_create_time_dim.sql
  - run/snowflake-8.13.1/scripts/tpcds/build/1_create_warehouse.sql
  - run/snowflake-8.13.1/scripts/tpcds/build/1_create_web_page.sql
  - run/snowflake-8.13.1/scripts/tpcds/build/1_create_web_returns.sql
  - run/snowflake-8.13.1/scripts/tpcds/build/1_create_web_sales.sql
  - run/snowflake-8.13.1/scripts/tpcds/build/1_create_web_site.sql
  - run/snowflake-8.13.1/scripts/tpcds/build/2_load_call_center.sql
  - run/snowflake-8.13.1/scripts/tpcds/build/2_load_catalog_page.sql
  - run/snowflake-8.13.1/scripts/tpcds/build/2_load_catalog_returns.sql
  - run/snowflake-8.13.1/scripts/tpcds/build/2_load_catalog_sales.sql
  - run/snowflake-8.13.1/scripts/tpcds/build/2_load_customer.sql
  - run/snowflake-8.13.1/scripts/tpcds/build/2_load_customer_address.sql
  - run/snowflake-8.13.1/scripts/tpcds/build/2_load_customer_demographics.sql
  - run/snowflake-8.13.1/scripts/tpcds/build/2_load_date_dim.sql
  - run/snowflake-8.13.1/scripts/tpcds/build/2_load_household_demographics.sql
  - run/snowflake-8.13.1/scripts/tpcds/build/2_load_income_band.sql
  - run/snowflake-8.13.1/scripts/tpcds/build/2_load_inventory.sql
  - run/snowflake-8.13.1/scripts/tpcds/build/2_load_item.sql
  - run/snowflake-8.13.1/scripts/tpcds/build/2_load_promotion.sql
  - run/snowflake-8.13.1/scripts/tpcds/build/2_load_reason.sql
  - run/snowflake-8.13.1/scripts/tpcds/build/2_load_ship_mode.sql
  - run/snowflake-8.13.1/scripts/tpcds/build/2_load_store.sql
  - run/snowflake-8.13.1/scripts/tpcds/build/2_load_store_returns.sql
  - run/snowflake-8.13.1/scripts/tpcds/build/2_load_store_sales.sql
  - run/snowflake-8.13.1/scripts/tpcds/build/2_load_time_dim.sql
  - run/snowflake-8.13.1/scripts/tpcds/build/2_load_warehouse.sql
  - run/snowflake-8.13.1/scripts/tpcds/build/2_load_web_page.sql
  - run/snowflake-8.13.1/scripts/tpcds/build/2_load_web_returns.sql
  - run/snowflake-8.13.1/scripts/tpcds/build/2_load_web_sales.sql
  - run/snowflake-8.13.1/scripts/tpcds/build/2_load_web_site.sql