# Description: W0: Original TPC-DS sequence
---
version: 1
id: w0_tpcds
phases:
- id: setup
  sessions:
  - tasks:
    - template_id: setup
- id: setup_data_maintenance
  sessions:
  - tasks:
    - template_id: setup_data_maintenance
    - template_id: setup_data_maintenance
    - template_id: setup_data_maintenance
    - template_id: setup_data_maintenance
- id: init
  sessions:
  - tasks:
    - template_id: init
- id: build
  sessions:
  - tasks:
    - template_id: build
- id: single_user_1
  sessions:
  - tasks:
    - template_id: single_user