# Description: Tasks Library
---
version: 1
task_templates:
# Create external tables needed for benchmark
- id: setup
  files:
  - run/trino-420/scripts/tpcds/setup/ddl-external-tables.sql
# Create data maintenance external tables needed for benchmark
- id: setup_data_maintenance
  files:
  - run/trino-420/scripts/tpcds/setup_data_maintenance/ddl-external-tables-refresh.sql
  parameter_values_file: run/auxiliary/tpcds/setup_data_maintenance/parameter_values.dat
# Create schema and drop existing tables
- id: init
  files:
  - run/trino-420/scripts/tpcds/init/init.sql
# Create benchmark tables and load data into them
- id: build
  files:
  - run/trino-420/scripts/tpcds/build/1_create_call_center.sql
  - run/trino-420/scripts/tpcds/build/1_create_catalog_page.sql
  - run/trino-420/scripts/tpcds/build/1_create_catalog_returns.sql
  - run/trino-420/scripts/tpcds/build/1_create_catalog_sales.sql
  - run/trino-420/scripts/tpcds/build/1_create_customer.sql
  - run/trino-420/scripts/tpcds/build/1_create_customer_address.sql
  - run/trino-420/scripts/tpcds/build/1_create_customer_demographics.sql
  - run/trino-420/scripts/tpcds/build/1_create_date_dim.sql
  - run/trino-420/scripts/tpcds/build/1_create_household_demographics.sql
  - run/trino-420/scripts/tpcds/build/1_create_income_band.sql
  - run/trino-420/scripts/tpcds/build/1_create_inventory.sql
  - run/trino-420/scripts/tpcds/build/1_create_item.sql
  - run/trino-420/scripts/tpcds/build/1_create_promotion.sql
  - run/trino-420/scripts/tpcds/build/1_create_reason.sql
  - run/trino-420/scripts/tpcds/build/1_create_ship_mode.sql
  - run/trino-420/scripts/tpcds/build/1_create_store.sql
  - run/trino-420/scripts/tpcds/build/1_create_store_returns.sql
  - run/trino-420/scripts/tpcds/build/1_create_store_sales.sql
  - run/trino-420/scripts/tpcds/build/1_create_time_dim.sql
  - run/trino-420/scripts/tpcds/build/1_create_warehouse.sql
  - run/trino-420/scripts/tpcds/build/1_create_web_page.sql
  - run/trino-420/scripts/tpcds/build/1_create_web_returns.sql
  - run/trino-420/scripts/tpcds/build/1_create_web_sales.sql
  - run/trino-420/scripts/tpcds/build/1_create_web_site.sql
  - run/trino-420/scripts/tpcds/build/2_load_call_center.sql
  - run/trino-420/scripts/tpcds/build/2_load_catalog_page.sql
  - run/trino-420/scripts/tpcds/build/2_load_catalog_returns.sql
  - run/trino-420/scripts/tpcds/build/2_load_catalog_sales.sql
  - run/trino-420/scripts/tpcds/build/2_load_customer.sql
  - run/trino-420/scripts/tpcds/build/2_load_customer_address.sql
  - run/trino-420/scripts/tpcds/build/2_load_customer_demographics.sql
  - run/trino-420/scripts/tpcds/build/2_load_date_dim.sql
  - run/trino-420/scripts/tpcds/build/2_load_household_demographics.sql
  - run/trino-420/scripts/tpcds/build/2_load_income_band.sql
  - run/trino-420/scripts/tpcds/build/2_load_inventory.sql
  - run/trino-420/scripts/tpcds/build/2_load_item.sql
  - run/trino-420/scripts/tpcds/build/2_load_promotion.sql
  - run/trino-420/scripts/tpcds/build/2_load_reason.sql
  - run/trino-420/scripts/tpcds/build/2_load_ship_mode.sql
  - run/trino-420/scripts/tpcds/build/2_load_store.sql
  - run/trino-420/scripts/tpcds/build/2_load_store_returns.sql
  - run/trino-420/scripts/tpcds/build/2_load_store_sales.sql
  - run/trino-420/scripts/tpcds/build/2_load_time_dim.sql
  - run/trino-420/scripts/tpcds/build/2_load_warehouse.sql
  - run/trino-420/scripts/tpcds/build/2_load_web_page.sql
  - run/trino-420/scripts/tpcds/build/2_load_web_returns.sql
  - run/trino-420/scripts/tpcds/build/2_load_web_sales.sql
  - run/trino-420/scripts/tpcds/build/2_load_web_site.sql
# Compute statistics for tables
- id: analyze
  files:
  - run/trino-420/scripts/tpcds/build/3_analyze_call_center.sql
  - run/trino-420/scripts/tpcds/build/3_analyze_catalog_page.sql
  - run/trino-420/scripts/tpcds/build/3_analyze_catalog_returns.sql
  - run/trino-420/scripts/tpcds/build/3_analyze_catalog_sales.sql
  - run/trino-420/scripts/tpcds/build/3_analyze_customer.sql
  - run/trino-420/scripts/tpcds/build/3_analyze_customer_address.sql
  - run/trino-420/scripts/tpcds/build/3_analyze_customer_demographics.sql
  - run/trino-420/scripts/tpcds/build/3_analyze_date_dim.sql
  - run/trino-420/scripts/tpcds/build/3_analyze_household_demographics.sql
  - run/trino-420/scripts/tpcds/build/3_analyze_income_band.sql
  - run/trino-420/scripts/tpcds/build/3_analyze_inventory.sql
  - run/trino-420/scripts/tpcds/build/3_analyze_item.sql
  - run/trino-420/scripts/tpcds/build/3_analyze_promotion.sql
  - run/trino-420/scripts/tpcds/build/3_analyze_reason.sql
  - run/trino-420/scripts/tpcds/build/3_analyze_ship_mode.sql
  - run/trino-420/scripts/tpcds/build/3_analyze_store.sql
  - run/trino-420/scripts/tpcds/build/3_analyze_store_returns.sql
  - run/trino-420/scripts/tpcds/build/3_analyze_store_sales.sql
  - run/trino-420/scripts/tpcds/build/3_analyze_time_dim.sql
  - run/trino-420/scripts/tpcds/build/3_analyze_warehouse.sql
  - run/trino-420/scripts/tpcds/build/3_analyze_web_page.sql
  - run/trino-420/scripts/tpcds/build/3_analyze_web_returns.sql
  - run/trino-420/scripts/tpcds/build/3_analyze_web_sales.sql
  - run/trino-420/scripts/tpcds/build/3_analyze_web_site.sql
# Execution of TPC-DS queries
- id: single_user
  files:
  - run/trino-420/scripts/tpcds/single_user/query1.sql
  - run/trino-420/scripts/tpcds/single_user/query2.sql
  - run/trino-420/scripts/tpcds/single_user/query3.sql
  - run/trino-420/scripts/tpcds/single_user/query4.sql
  - run/trino-420/scripts/tpcds/single_user/query5.sql
  - run/trino-420/scripts/tpcds/single_user/query6.sql
  - run/trino-420/scripts/tpcds/single_user/query7.sql
  - run/trino-420/scripts/tpcds/single_user/query8.sql
  - run/trino-420/scripts/tpcds/single_user/query9.sql
  - run/trino-420/scripts/tpcds/single_user/query10.sql
  - run/trino-420/scripts/tpcds/single_user/query11.sql
  - run/trino-420/scripts/tpcds/single_user/query12.sql
  - run/trino-420/scripts/tpcds/single_user/query13.sql
  - run/trino-420/scripts/tpcds/single_user/query14.sql
  - run/trino-420/scripts/tpcds/single_user/query15.sql
  - run/trino-420/scripts/tpcds/single_user/query16.sql
  - run/trino-420/scripts/tpcds/single_user/query17.sql
  - run/trino-420/scripts/tpcds/single_user/query18.sql
  - run/trino-420/scripts/tpcds/single_user/query19.sql
  - run/trino-420/scripts/tpcds/single_user/query20.sql
  - run/trino-420/scripts/tpcds/single_user/query21.sql
  - run/trino-420/scripts/tpcds/single_user/query22.sql
  - run/trino-420/scripts/tpcds/single_user/query23.sql
  - run/trino-420/scripts/tpcds/single_user/query24.sql
  - run/trino-420/scripts/tpcds/single_user/query25.sql
  - run/trino-420/scripts/tpcds/single_user/query26.sql
  - run/trino-420/scripts/tpcds/single_user/query27.sql
  - run/trino-420/scripts/tpcds/single_user/query28.sql
  - run/trino-420/scripts/tpcds/single_user/query29.sql
  - run/trino-420/scripts/tpcds/single_user/query30.sql
  - run/trino-420/scripts/tpcds/single_user/query31.sql
  - run/trino-420/scripts/tpcds/single_user/query32.sql
  - run/trino-420/scripts/tpcds/single_user/query33.sql
  - run/trino-420/scripts/tpcds/single_user/query34.sql
  - run/trino-420/scripts/tpcds/single_user/query35.sql
  - run/trino-420/scripts/tpcds/single_user/query36.sql
  - run/trino-420/scripts/tpcds/single_user/query37.sql
  - run/trino-420/scripts/tpcds/single_user/query38.sql
  - run/trino-420/scripts/tpcds/single_user/query39.sql
  - run/trino-420/scripts/tpcds/single_user/query40.sql
  - run/trino-420/scripts/tpcds/single_user/query41.sql
  - run/trino-420/scripts/tpcds/single_user/query42.sql
  - run/trino-420/scripts/tpcds/single_user/query43.sql
  - run/trino-420/scripts/tpcds/single_user/query44.sql
  - run/trino-420/scripts/tpcds/single_user/query45.sql
  - run/trino-420/scripts/tpcds/single_user/query46.sql
  - run/trino-420/scripts/tpcds/single_user/query47.sql
  - run/trino-420/scripts/tpcds/single_user/query48.sql
  - run/trino-420/scripts/tpcds/single_user/query49.sql
  - run/trino-420/scripts/tpcds/single_user/query50.sql
  - run/trino-420/scripts/tpcds/single_user/query51.sql
  - run/trino-420/scripts/tpcds/single_user/query52.sql
  - run/trino-420/scripts/tpcds/single_user/query53.sql
  - run/trino-420/scripts/tpcds/single_user/query54.sql
  - run/trino-420/scripts/tpcds/single_user/query55.sql
  - run/trino-420/scripts/tpcds/single_user/query56.sql
  - run/trino-420/scripts/tpcds/single_user/query57.sql
  - run/trino-420/scripts/tpcds/single_user/query58.sql
  - run/trino-420/scripts/tpcds/single_user/query59.sql
  - run/trino-420/scripts/tpcds/single_user/query60.sql
  - run/trino-420/scripts/tpcds/single_user/query61.sql
  - run/trino-420/scripts/tpcds/single_user/query62.sql
  - run/trino-420/scripts/tpcds/single_user/query63.sql
  - run/trino-420/scripts/tpcds/single_user/query64.sql
  - run/trino-420/scripts/tpcds/single_user/query65.sql
  - run/trino-420/scripts/tpcds/single_user/query66.sql
  - run/trino-420/scripts/tpcds/single_user/query67.sql
  - run/trino-420/scripts/tpcds/single_user/query68.sql
  - run/trino-420/scripts/tpcds/single_user/query69.sql
  - run/trino-420/scripts/tpcds/single_user/query70.sql
  - run/trino-420/scripts/tpcds/single_user/query71.sql
  - run/trino-420/scripts/tpcds/single_user/query72.sql
  - run/trino-420/scripts/tpcds/single_user/query73.sql
  - run/trino-420/scripts/tpcds/single_user/query74.sql
  - run/trino-420/scripts/tpcds/single_user/query75.sql
  - run/trino-420/scripts/tpcds/single_user/query76.sql
  - run/trino-420/scripts/tpcds/single_user/query77.sql
  - run/trino-420/scripts/tpcds/single_user/query78.sql
  - run/trino-420/scripts/tpcds/single_user/query79.sql
  - run/trino-420/scripts/tpcds/single_user/query80.sql
  - run/trino-420/scripts/tpcds/single_user/query81.sql
  - run/trino-420/scripts/tpcds/single_user/query82.sql
  - run/trino-420/scripts/tpcds/single_user/query83.sql
  - run/trino-420/scripts/tpcds/single_user/query84.sql
  - run/trino-420/scripts/tpcds/single_user/query85.sql
  - run/trino-420/scripts/tpcds/single_user/query86.sql
  - run/trino-420/scripts/tpcds/single_user/query87.sql
  - run/trino-420/scripts/tpcds/single_user/query88.sql
  - run/trino-420/scripts/tpcds/single_user/query89.sql
  - run/trino-420/scripts/tpcds/single_user/query90.sql
  - run/trino-420/scripts/tpcds/single_user/query91.sql
  - run/trino-420/scripts/tpcds/single_user/query92.sql
  - run/trino-420/scripts/tpcds/single_user/query93.sql
  - run/trino-420/scripts/tpcds/single_user/query94.sql
  - run/trino-420/scripts/tpcds/single_user/query95.sql
  - run/trino-420/scripts/tpcds/single_user/query96.sql
  - run/trino-420/scripts/tpcds/single_user/query97.sql
  - run/trino-420/scripts/tpcds/single_user/query98.sql
  - run/trino-420/scripts/tpcds/single_user/query99.sql
  permutation_orders_path: run/auxiliary/tpcds/single_user/permutation_orders/
# Execution of TPC-DS data maintenance queries
- id: data_maintenance
  files:
  - run/trino-420/scripts/tpcds/data_maintenance/DF_CS.sql
  - run/trino-420/scripts/tpcds/data_maintenance/DF_I.sql
  - run/trino-420/scripts/tpcds/data_maintenance/DF_SS.sql
  - run/trino-420/scripts/tpcds/data_maintenance/DF_WS.sql
  - run/trino-420/scripts/tpcds/data_maintenance/LF_CR.sql
  - run/trino-420/scripts/tpcds/data_maintenance/LF_CS.sql
  - run/trino-420/scripts/tpcds/data_maintenance/LF_I.sql
  - run/trino-420/scripts/tpcds/data_maintenance/LF_SR.sql
  - run/trino-420/scripts/tpcds/data_maintenance/LF_SS.sql
  - run/trino-420/scripts/tpcds/data_maintenance/LF_WR.sql
  - run/trino-420/scripts/tpcds/data_maintenance/LF_WS.sql
  parameter_values_file: run/auxiliary/tpcds/data_maintenance/parameter_values.dat
# Execution of optimize on all benchmark tables
- id: optimize
  files:
  - run/trino-420/scripts/tpcds/optimize/o_call_center.sql
  - run/trino-420/scripts/tpcds/optimize/o_catalog_page.sql
  - run/trino-420/scripts/tpcds/optimize/o_catalog_returns.sql
  - run/trino-420/scripts/tpcds/optimize/o_catalog_sales.sql
  - run/trino-420/scripts/tpcds/optimize/o_customer.sql
  - run/trino-420/scripts/tpcds/optimize/o_customer_address.sql
  - run/trino-420/scripts/tpcds/optimize/o_customer_demographics.sql
  - run/trino-420/scripts/tpcds/optimize/o_date_dim.sql
  - run/trino-420/scripts/tpcds/optimize/o_household_demographics.sql
  - run/trino-420/scripts/tpcds/optimize/o_income_band.sql
  - run/trino-420/scripts/tpcds/optimize/o_inventory.sql
  - run/trino-420/scripts/tpcds/optimize/o_item.sql
  - run/trino-420/scripts/tpcds/optimize/o_promotion.sql
  - run/trino-420/scripts/tpcds/optimize/o_reason.sql
  - run/trino-420/scripts/tpcds/optimize/o_ship_mode.sql
  - run/trino-420/scripts/tpcds/optimize/o_store.sql
  - run/trino-420/scripts/tpcds/optimize/o_store_returns.sql
  - run/trino-420/scripts/tpcds/optimize/o_store_sales.sql
  - run/trino-420/scripts/tpcds/optimize/o_time_dim.sql
  - run/trino-420/scripts/tpcds/optimize/o_warehouse.sql
  - run/trino-420/scripts/tpcds/optimize/o_web_page.sql
  - run/trino-420/scripts/tpcds/optimize/o_web_returns.sql
  - run/trino-420/scripts/tpcds/optimize/o_web_sales.sql
  - run/trino-420/scripts/tpcds/optimize/o_web_site.sql
# Execution of optimize on all benchmark tables but splitting optimization
# of partitioned tables into batches by relying on dependent task executor
- id: optimize_split
  custom_task_executor: com.microsoft.lst_bench.task.custom.DependentTaskExecutor
  files:
  - run/trino-420/scripts/tpcds/optimize/o_call_center.sql
  - run/trino-420/scripts/tpcds/optimize/o_catalog_page.sql
  - run/trino-420/scripts/tpcds/optimize_split/o_catalog_returns_SELECT.sql
  - run/trino-420/scripts/tpcds/optimize_split/o_catalog_returns_IN.sql
  - run/trino-420/scripts/tpcds/optimize_split/o_catalog_returns_NULL.sql
  - run/trino-420/scripts/tpcds/optimize_split/o_catalog_sales_SELECT.sql
  - run/trino-420/scripts/tpcds/optimize_split/o_catalog_sales_IN.sql
  - run/trino-420/scripts/tpcds/optimize_split/o_catalog_sales_NULL.sql
  - run/trino-420/scripts/tpcds/optimize/o_customer.sql
  - run/trino-420/scripts/tpcds/optimize/o_customer_address.sql
  - run/trino-420/scripts/tpcds/optimize/o_customer_demographics.sql
  - run/trino-420/scripts/tpcds/optimize/o_date_dim.sql
  - run/trino-420/scripts/tpcds/optimize/o_household_demographics.sql
  - run/trino-420/scripts/tpcds/optimize/o_income_band.sql
  - run/trino-420/scripts/tpcds/optimize_split/o_inventory_SELECT.sql
  - run/trino-420/scripts/tpcds/optimize_split/o_inventory_IN.sql
  - run/trino-420/scripts/tpcds/optimize_split/o_inventory_NULL.sql
  - run/trino-420/scripts/tpcds/optimize/o_item.sql
  - run/trino-420/scripts/tpcds/optimize/o_promotion.sql
  - run/trino-420/scripts/tpcds/optimize/o_reason.sql
  - run/trino-420/scripts/tpcds/optimize/o_ship_mode.sql
  - run/trino-420/scripts/tpcds/optimize/o_store.sql
  - run/trino-420/scripts/tpcds/optimize_split/o_store_returns_SELECT.sql
  - run/trino-420/scripts/tpcds/optimize_split/o_store_returns_IN.sql
  - run/trino-420/scripts/tpcds/optimize_split/o_store_returns_NULL.sql
  - run/trino-420/scripts/tpcds/optimize_split/o_store_sales_SELECT.sql
  - run/trino-420/scripts/tpcds/optimize_split/o_store_sales_IN.sql
  - run/trino-420/scripts/tpcds/optimize_split/o_store_sales_NULL.sql
  - run/trino-420/scripts/tpcds/optimize/o_time_dim.sql
  - run/trino-420/scripts/tpcds/optimize/o_warehouse.sql
  - run/trino-420/scripts/tpcds/optimize/o_web_page.sql
  - run/trino-420/scripts/tpcds/optimize_split/o_web_returns_SELECT.sql
  - run/trino-420/scripts/tpcds/optimize_split/o_web_returns_IN.sql
  - run/trino-420/scripts/tpcds/optimize_split/o_web_returns_NULL.sql
  - run/trino-420/scripts/tpcds/optimize_split/o_web_sales_SELECT.sql
  - run/trino-420/scripts/tpcds/optimize_split/o_web_sales_IN.sql
  - run/trino-420/scripts/tpcds/optimize_split/o_web_sales_NULL.sql
  - run/trino-420/scripts/tpcds/optimize/o_web_site.sql
