# Description: WP1: Longevity
---
version: 1
id: wp1_longevity
phases:
- id: setup
  sessions:
  - tasks:
    - template_id: setup
- id: setup_data_maintenance
  sessions:
  - tasks:
    - template_id: setup_data_maintenance
    - template_id: setup_data_maintenance
    - template_id: setup_data_maintenance
    - template_id: setup_data_maintenance
    - template_id: setup_data_maintenance
    - template_id: setup_data_maintenance
    - template_id: setup_data_maintenance
    - template_id: setup_data_maintenance
    - template_id: setup_data_maintenance
    - template_id: setup_data_maintenance
- id: init
  sessions:
  - tasks:
    - template_id: init
- id: build
  sessions:
  - tasks:
    - template_id: build
- id: data_maintenance_1
  sessions:
  - tasks:
    - template_id: data_maintenance_delta_dependent
      custom_task_executor: DependentTaskExecutor
    - template_id: data_maintenance_delta_dependent
      custom_task_executor: DependentTaskExecutor
- id: single_user_1
  sessions:
  - tasks:
    - template_id: single_user