# Description: W0: Original TPC-DS sequence
---
version: 1
id: w0_tpcds_hudi
phases:
- id: setup
  sessions:
  - tasks:
    - template_id: setup
- id: setup_data_maintenance
  sessions:
  - tasks:
    - template_id: setup_data_maintenance
    - template_id: setup_data_maintenance
    - template_id: setup_data_maintenance
    - template_id: setup_data_maintenance
- id: init
  sessions:
  - tasks:
    - template_id: init
- id: build
  sessions:
  - tasks:
    - template_id: build
      replace_regex:
      - pattern: '(?i)varchar\(.*\)|char\(.*\)'
        replacement: 'string'
- id: single_user
  sessions:
  - tasks:
    - template_id: single_user
- id: throughput_1
  sessions:
  - tasks:
    - template_id: single_user
      permute_order: true
  - tasks:
    - template_id: single_user
      permute_order: true
  - tasks:
    - template_id: single_user
      permute_order: true
  - tasks:
    - template_id: single_user
      permute_order: true
- id: data_maintenance_1
  sessions:
  - tasks:
    - template_id: data_maintenance_hudi
    - template_id: data_maintenance_hudi
- id: throughput_2
  sessions:
  - tasks:
    - template_id: single_user
      permute_order: true
  - tasks:
    - template_id: single_user
      permute_order: true
  - tasks:
    - template_id: single_user
      permute_order: true
  - tasks:
    - template_id: single_user
      permute_order: true
- id: data_maintenance_2
  sessions:
  - tasks:
    - template_id: data_maintenance_hudi
    - template_id: data_maintenance_hudi
