# Description: WP1: Longevity
---
version: 1
id: wp1_longevity
phases:
- id: setup
  sessions:
  - tasks:
    - template_id: setup
- id: setup_data_maintenance
  sessions:
  - tasks:
    - template_id: setup_data_maintenance
    - template_id: setup_data_maintenance
    - template_id: setup_data_maintenance
    - template_id: setup_data_maintenance
    - template_id: setup_data_maintenance
    - template_id: setup_data_maintenance
    - template_id: setup_data_maintenance
    - template_id: setup_data_maintenance
    - template_id: setup_data_maintenance
    - template_id: setup_data_maintenance
- id: init
  sessions:
  - tasks:
    - template_id: init
- id: build
  sessions:
  - tasks:
    - template_id: build
- id: single_user_1
  sessions:
  - tasks:
    - template_id: single_user
- id: data_maintenance_dependent_1
  sessions:
  - tasks:
    - template_id: data_maintenance_dependent
      custom_task_executor: com.microsoft.lst_bench.task.custom.DependentTaskExecutor
      task_executor_arguments:
        dependent_task_batch_size: 1000
    - template_id: data_maintenance_dependent
      custom_task_executor: com.microsoft.lst_bench.task.custom.DependentTaskExecutor
      task_executor_arguments:
        dependent_task_batch_size: 1000
- id: single_user_2
  sessions:
  - tasks:
    - template_id: single_user
- id: data_maintenance_dependent_2
  sessions:
  - tasks:
    - template_id: data_maintenance_dependent
      custom_task_executor: com.microsoft.lst_bench.task.custom.DependentTaskExecutor
      task_executor_arguments:
        dependent_task_batch_size: 1000
    - template_id: data_maintenance_dependent
      custom_task_executor: com.microsoft.lst_bench.task.custom.DependentTaskExecutor
      task_executor_arguments:
        dependent_task_batch_size: 1000
- id: single_user_3
  sessions:
  - tasks:
    - template_id: single_user
- id: data_maintenance_dependent_3
  sessions:
  - tasks:
    - template_id: data_maintenance_dependent
      custom_task_executor: com.microsoft.lst_bench.task.custom.DependentTaskExecutor
      task_executor_arguments:
        dependent_task_batch_size: 1000
    - template_id: data_maintenance_dependent
      custom_task_executor: com.microsoft.lst_bench.task.custom.DependentTaskExecutor
      task_executor_arguments:
        dependent_task_batch_size: 1000
- id: single_user_4
  sessions:
  - tasks:
    - template_id: single_user
- id: data_maintenance_dependent_4
  sessions:
  - tasks:
    - template_id: data_maintenance_dependent
      custom_task_executor: com.microsoft.lst_bench.task.custom.DependentTaskExecutor
      task_executor_arguments:
        dependent_task_batch_size: 1000
    - template_id: data_maintenance_dependent
      custom_task_executor: com.microsoft.lst_bench.task.custom.DependentTaskExecutor
      task_executor_arguments:
        dependent_task_batch_size: 1000
- id: single_user_5
  sessions:
  - tasks:
    - template_id: single_user
- id: data_maintenance_dependent_5
  sessions:
  - tasks:
    - template_id: template_id: data_maintenance_dependent
      custom_task_executor: com.microsoft.lst_bench.task.custom.DependentTaskExecutor
      task_executor_arguments:
        dependent_task_batch_size: 1000
    - template_id: data_maintenance_dependent
      custom_task_executor: com.microsoft.lst_bench.task.custom.DependentTaskExecutor
      task_executor_arguments:
        dependent_task_batch_size: 1000
- id: single_user_6
  sessions:
  - tasks:
    - template_id: single_user
