# Description: Experiment Configuration
---
version: 1
id: setup_experiment
repetitions: 1
# Metadata accepts any key-value that we want to register together with the experiment run.
metadata:
  system: trino
  system_version: 420
  scale_factor: "${EXP_SCALE_FACTOR}"
  machine: "${EXP_MACHINE}"
  cluster_size: "${EXP_CLUSTER_SIZE}"
# The following parameter values will be used to replace the variables in the workload statements.
parameter_values:
  external_catalog: hive
  external_database: "external_tpcds_sf_${EXP_SCALE_FACTOR}"
  external_table_format: textfile
  external_data_path: "abfss://${DATA_STORAGE_ACCOUNT_CONTAINER}@${DATA_STORAGE_ACCOUNT}.dfs.core.windows.net/tpc-ds/csv/sf_${EXP_SCALE_FACTOR}/"
  external_options_suffix: ''
  external_tblproperties_suffix: ", textfile_field_separator=',', null_format='', skip_header_line_count=1"
