# Description: Tasks Library
---
version: 1
task_templates:
# Create external tables needed for benchmark
- id: setup
  files:
  - src/main/resources/scripts/tpcds/setup/trino/ddl-external-tables.sql
# Create data maintenance external tables needed for benchmark
- id: setup_data_maintenance
  files:
  - src/main/resources/scripts/tpcds/setup_data_maintenance/trino/ddl-external-tables-refresh.sql
  parameter_values_file: src/main/resources/auxiliary/tpcds/setup_data_maintenance/parameter_values.dat
# Create schema and drop existing tables
- id: init
  files:
  - src/main/resources/scripts/tpcds/init/trino/init.sql
# Create benchmark tables and load data into them
- id: build
  files:
  - src/main/resources/scripts/tpcds/build/trino/1_create_call_center.sql
  - src/main/resources/scripts/tpcds/build/trino/1_create_catalog_page.sql
  - src/main/resources/scripts/tpcds/build/trino/1_create_catalog_returns.sql
  - src/main/resources/scripts/tpcds/build/trino/1_create_catalog_sales.sql
  - src/main/resources/scripts/tpcds/build/trino/1_create_customer.sql
  - src/main/resources/scripts/tpcds/build/trino/1_create_customer_address.sql
  - src/main/resources/scripts/tpcds/build/trino/1_create_customer_demographics.sql
  - src/main/resources/scripts/tpcds/build/trino/1_create_date_dim.sql
  - src/main/resources/scripts/tpcds/build/trino/1_create_household_demographics.sql
  - src/main/resources/scripts/tpcds/build/trino/1_create_income_band.sql
  - src/main/resources/scripts/tpcds/build/trino/1_create_inventory.sql
  - src/main/resources/scripts/tpcds/build/trino/1_create_item.sql
  - src/main/resources/scripts/tpcds/build/trino/1_create_promotion.sql
  - src/main/resources/scripts/tpcds/build/trino/1_create_reason.sql
  - src/main/resources/scripts/tpcds/build/trino/1_create_ship_mode.sql
  - src/main/resources/scripts/tpcds/build/trino/1_create_store.sql
  - src/main/resources/scripts/tpcds/build/trino/1_create_store_returns.sql
  - src/main/resources/scripts/tpcds/build/trino/1_create_store_sales.sql
  - src/main/resources/scripts/tpcds/build/trino/1_create_time_dim.sql
  - src/main/resources/scripts/tpcds/build/trino/1_create_warehouse.sql
  - src/main/resources/scripts/tpcds/build/trino/1_create_web_page.sql
  - src/main/resources/scripts/tpcds/build/trino/1_create_web_returns.sql
  - src/main/resources/scripts/tpcds/build/trino/1_create_web_sales.sql
  - src/main/resources/scripts/tpcds/build/trino/1_create_web_site.sql
  - src/main/resources/scripts/tpcds/build/trino/2_load_call_center.sql
  - src/main/resources/scripts/tpcds/build/trino/2_load_catalog_page.sql
  - src/main/resources/scripts/tpcds/build/trino/2_load_catalog_returns.sql
  - src/main/resources/scripts/tpcds/build/trino/2_load_catalog_sales.sql
  - src/main/resources/scripts/tpcds/build/trino/2_load_customer.sql
  - src/main/resources/scripts/tpcds/build/trino/2_load_customer_address.sql
  - src/main/resources/scripts/tpcds/build/trino/2_load_customer_demographics.sql
  - src/main/resources/scripts/tpcds/build/trino/2_load_date_dim.sql
  - src/main/resources/scripts/tpcds/build/trino/2_load_household_demographics.sql
  - src/main/resources/scripts/tpcds/build/trino/2_load_income_band.sql
  - src/main/resources/scripts/tpcds/build/trino/2_load_inventory.sql
  - src/main/resources/scripts/tpcds/build/trino/2_load_item.sql
  - src/main/resources/scripts/tpcds/build/trino/2_load_promotion.sql
  - src/main/resources/scripts/tpcds/build/trino/2_load_reason.sql
  - src/main/resources/scripts/tpcds/build/trino/2_load_ship_mode.sql
  - src/main/resources/scripts/tpcds/build/trino/2_load_store.sql
  - src/main/resources/scripts/tpcds/build/trino/2_load_store_returns.sql
  - src/main/resources/scripts/tpcds/build/trino/2_load_store_sales.sql
  - src/main/resources/scripts/tpcds/build/trino/2_load_time_dim.sql
  - src/main/resources/scripts/tpcds/build/trino/2_load_warehouse.sql
  - src/main/resources/scripts/tpcds/build/trino/2_load_web_page.sql
  - src/main/resources/scripts/tpcds/build/trino/2_load_web_returns.sql
  - src/main/resources/scripts/tpcds/build/trino/2_load_web_sales.sql
  - src/main/resources/scripts/tpcds/build/trino/2_load_web_site.sql
# Compute statistics for tables
- id: analyze
  files:
  - src/main/resources/scripts/tpcds/build/trino/3_analyze_call_center.sql
  - src/main/resources/scripts/tpcds/build/trino/3_analyze_catalog_page.sql
  - src/main/resources/scripts/tpcds/build/trino/3_analyze_catalog_returns.sql
  - src/main/resources/scripts/tpcds/build/trino/3_analyze_catalog_sales.sql
  - src/main/resources/scripts/tpcds/build/trino/3_analyze_customer.sql
  - src/main/resources/scripts/tpcds/build/trino/3_analyze_customer_address.sql
  - src/main/resources/scripts/tpcds/build/trino/3_analyze_customer_demographics.sql
  - src/main/resources/scripts/tpcds/build/trino/3_analyze_date_dim.sql
  - src/main/resources/scripts/tpcds/build/trino/3_analyze_household_demographics.sql
  - src/main/resources/scripts/tpcds/build/trino/3_analyze_income_band.sql
  - src/main/resources/scripts/tpcds/build/trino/3_analyze_inventory.sql
  - src/main/resources/scripts/tpcds/build/trino/3_analyze_item.sql
  - src/main/resources/scripts/tpcds/build/trino/3_analyze_promotion.sql
  - src/main/resources/scripts/tpcds/build/trino/3_analyze_reason.sql
  - src/main/resources/scripts/tpcds/build/trino/3_analyze_ship_mode.sql
  - src/main/resources/scripts/tpcds/build/trino/3_analyze_store.sql
  - src/main/resources/scripts/tpcds/build/trino/3_analyze_store_returns.sql
  - src/main/resources/scripts/tpcds/build/trino/3_analyze_store_sales.sql
  - src/main/resources/scripts/tpcds/build/trino/3_analyze_time_dim.sql
  - src/main/resources/scripts/tpcds/build/trino/3_analyze_warehouse.sql
  - src/main/resources/scripts/tpcds/build/trino/3_analyze_web_page.sql
  - src/main/resources/scripts/tpcds/build/trino/3_analyze_web_returns.sql
  - src/main/resources/scripts/tpcds/build/trino/3_analyze_web_sales.sql
  - src/main/resources/scripts/tpcds/build/trino/3_analyze_web_site.sql
# Execution of TPC-DS queries
- id: single_user
  files:
  - src/main/resources/scripts/tpcds/single_user/trino/query1.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query2.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query3.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query4.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query5.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query6.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query7.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query8.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query9.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query10.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query11.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query12.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query13.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query14.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query15.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query16.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query17.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query18.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query19.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query20.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query21.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query22.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query23.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query24.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query25.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query26.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query27.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query28.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query29.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query30.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query31.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query32.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query33.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query34.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query35.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query36.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query37.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query38.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query39.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query40.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query41.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query42.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query43.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query44.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query45.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query46.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query47.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query48.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query49.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query50.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query51.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query52.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query53.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query54.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query55.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query56.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query57.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query58.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query59.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query60.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query61.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query62.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query63.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query64.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query65.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query66.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query67.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query68.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query69.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query70.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query71.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query72.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query73.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query74.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query75.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query76.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query77.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query78.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query79.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query80.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query81.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query82.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query83.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query84.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query85.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query86.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query87.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query88.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query89.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query90.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query91.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query92.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query93.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query94.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query95.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query96.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query97.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query98.sql
  - src/main/resources/scripts/tpcds/single_user/trino/query99.sql
  permutation_orders_path: src/main/resources/auxiliary/tpcds/single_user/permutation_orders/
# Execution of TPC-DS data maintenance queries
- id: data_maintenance
  files:
  - src/main/resources/scripts/tpcds/data_maintenance/trino/DF_CS.sql
  - src/main/resources/scripts/tpcds/data_maintenance/trino/DF_I.sql
  - src/main/resources/scripts/tpcds/data_maintenance/trino/DF_SS.sql
  - src/main/resources/scripts/tpcds/data_maintenance/trino/DF_WS.sql
  - src/main/resources/scripts/tpcds/data_maintenance/trino/LF_CR.sql
  - src/main/resources/scripts/tpcds/data_maintenance/trino/LF_CS.sql
  - src/main/resources/scripts/tpcds/data_maintenance/trino/LF_I.sql
  - src/main/resources/scripts/tpcds/data_maintenance/trino/LF_SR.sql
  - src/main/resources/scripts/tpcds/data_maintenance/trino/LF_SS.sql
  - src/main/resources/scripts/tpcds/data_maintenance/trino/LF_WR.sql
  - src/main/resources/scripts/tpcds/data_maintenance/trino/LF_WS.sql
  parameter_values_file: src/main/resources/auxiliary/tpcds/data_maintenance/parameter_values.dat
# Execution of optimize on all benchmark tables
- id: optimize
  files:
  - src/main/resources/scripts/tpcds/optimize/trino/o_call_center.sql
  - src/main/resources/scripts/tpcds/optimize/trino/o_catalog_page.sql
  - src/main/resources/scripts/tpcds/optimize/trino/o_catalog_returns.sql
  - src/main/resources/scripts/tpcds/optimize/trino/o_catalog_sales.sql
  - src/main/resources/scripts/tpcds/optimize/trino/o_customer.sql
  - src/main/resources/scripts/tpcds/optimize/trino/o_customer_address.sql
  - src/main/resources/scripts/tpcds/optimize/trino/o_customer_demographics.sql
  - src/main/resources/scripts/tpcds/optimize/trino/o_date_dim.sql
  - src/main/resources/scripts/tpcds/optimize/trino/o_household_demographics.sql
  - src/main/resources/scripts/tpcds/optimize/trino/o_income_band.sql
  - src/main/resources/scripts/tpcds/optimize/trino/o_inventory.sql
  - src/main/resources/scripts/tpcds/optimize/trino/o_item.sql
  - src/main/resources/scripts/tpcds/optimize/trino/o_promotion.sql
  - src/main/resources/scripts/tpcds/optimize/trino/o_reason.sql
  - src/main/resources/scripts/tpcds/optimize/trino/o_ship_mode.sql
  - src/main/resources/scripts/tpcds/optimize/trino/o_store.sql
  - src/main/resources/scripts/tpcds/optimize/trino/o_store_returns.sql
  - src/main/resources/scripts/tpcds/optimize/trino/o_store_sales.sql
  - src/main/resources/scripts/tpcds/optimize/trino/o_time_dim.sql
  - src/main/resources/scripts/tpcds/optimize/trino/o_warehouse.sql
  - src/main/resources/scripts/tpcds/optimize/trino/o_web_page.sql
  - src/main/resources/scripts/tpcds/optimize/trino/o_web_returns.sql
  - src/main/resources/scripts/tpcds/optimize/trino/o_web_sales.sql
  - src/main/resources/scripts/tpcds/optimize/trino/o_web_site.sql
